export const macrozonas = {
  NORORIENTE: 'NORORIENTE',
  NORTE: 'NORTE',
  NORPONIENTE: 'NORPONIENTE',
  CENTRO: 'CENTRO',
  SURPONIENTE: 'SURPONIENTE',
  SUR: 'SUR',
  SURORIENTE: 'SURORIENTE',
};

export const diasSemana = {
  L: 'Lunes',
  M: 'Martes',
  I: 'Miércoles',
  J: 'Jueves',
  V: 'Viernes',
};

export const diasLogisticos = {
  A2: 'A2',
  A3: 'A3',
  A4: 'A4',
  A5: 'A5',
  B2: 'B2',
  B3: 'B3',
  B4: 'B4',
  B5: 'B5',
  C2: 'C2',
  C3: 'C3',
  C4: 'C4',
  C5: 'C5',
  D2: 'D2',
  D3: 'D3',
  D4: 'D4',
  D5: 'D5',
  E2: 'E2',
  E3: 'E3',
  E4: 'E4',
  E5: 'E5',
};

export const diasLogisticosCompleto = {
  A2: 'A2',
  A3: 'A3',
  A4: 'A4',
  A5: 'A5',
  B2: 'B2',
  B3: 'B3',
  B4: 'B4',
  B5: 'B5',
  C2: 'C2',
  C3: 'C3',
  C4: 'C4',
  C5: 'C5',
  D2: 'D2',
  D3: 'D3',
  D4: 'D4',
  D5: 'D5',
  E2: 'E2',
  E3: 'E3',
  E4: 'E4',
  E5: 'E5',
  F2: 'F2',
  F3: 'F3',
  F4: 'F4',
  F5: 'F5',
  G2: 'G2',
  G3: 'G3',
  G4: 'G4',
  G5: 'G5',
};

export const sublineas = {
  1: 'Aromatización',
  2: 'Pilas',
  3: 'Bacteriostaticos',
  4: 'Contenedores',
  5: 'Filtros Urinarios',
  6: 'Pilas Bioservicios',
  7: 'Otros',
  8: 'Plagas',
  9: 'Secadores de mano',
  10: 'Jabones',
  11: 'Ozono',
  12: 'Maquinas',
  13: 'Bioservicios',
  14: 'Aroma Concept',
  15: 'Tissue',
};

export const columnasArchivoNotasVenta: string[] = [
  'notaventa',
  'tipo_nv',
  'sucursal',
  'rut_clie',
  'razsoc',
  'nombrefantasia',
  'direccion_log',
  'bloqueo',
  'frec_linea',
  'sublinea',
  'item',
  'codigo',
  'nombre',
  'terminado',
  'facturable',
  'despachable',
  'estado_servicio',
  'cantidad',
  'preciouni',
  'descuentoitem',
  'descuentototal',
  'bodega',
  'logistica',
  'semana_logistica',
  'ciclos',
  'ciclo_realizado',
  'rutero',
  'dìa_log',
  'fechainicio',
  'fechatermino',
  'mesbonificado',
];

export const columnasArchivoRestricciones: string[] = [
  'Llave de búsqueda',
  'Supervisor',
  'Ejecutivo',
  'Tipo Contrato',
  'Grupo Logistico',
  'notaventa',
  'Comunas por rut_cliente',
  'rut_clie',
  'nombrefantasia',
  'Holding',
  'direccion_log',
  'direccion_log_editada',
  'Comuna Normalizada',
  'Latitud',
  'Longitud',
  'Día Logístico',
  'N° Visita',
  'Visitas Totales',
  'Desde',
  'Hasta',
  'Restricción adicional',
  'Restricción dia con palabra',
  'Restricciíon día especifico',
  'Observaciones',
  'Semana Logística',
  'ciclos',
  'Zonas (sectores)',
  'Suma de Tiempo total (min) incluyendo factor en duplas',
  'Restriccion Pendiente',
  'Restricción horaria',
  'Comentario - R1',
  'Aux - R1',
  'Restricción día',
  'Comentario - R2',
  'Aux - R2',
  'Restricción Semana',
  'Comentario - R3',
  'Restricción de inducción',
  'Comentario - R4',
  'Observación',
];

export const columnasArchivoTiemposTeoricos: string[] = [
  'cantidad',
  'Aromatización',
  'Bacteriostaticos',
  'Ozono',
  'Contenedores',
  'Filtros Urinarios',
  'Jabones',
  'Bioservicios',
  'plagas',
  'Otros',
  'Contenedores cambio bolsa',
  'Bioservicios mini',
  'Plagas/Repelente',
  'Plagas/Desinsectacion',
  'Plagas/cortina/spray',
  'Plagas/Sanitizacion',
  'Maquinas',
  'Secadores de mano',
  'Plagas ADICIONAL',
  'Plagas/Sanitizacion ind',
  'Plagas TRAMPA',
  'Aromatización/Nebulizador',
  'Plagas UV',
  'TOTEM',
  'Bacteriostaticos',
  'PORTA TOALLA',
];

export const columnasArchivoGruposLogisticos: string[] = [
  'Grupo Logistico',
  'Ejecutivos',
  'Zona',
  'Dupla',
];

export const columnasArchivoDarDeBajaMasivo: string[] = ['notaventa'];
